### Test de Création de Membre (Mot de passe par défaut)
# Le mot de passe par défaut sera les 6 derniers chiffres du téléphone : 556677
POST http://localhost:3000/api/membres
Content-Type: application/json

{
  "nomComplet": "Test Password Gen",
  "telephone": "+24381144556677",
  "email": "testgen@mwangaza.com",
  "typeCompte": "Principal",
  "sexe": "M",
  "statut": "actif",
  "dateAdhesion": "2026-03-09T10:00:00Z"
}

### Connexion Membre (First Access)
# On utilise le PIN par défaut: 556677
# Note: Remplacez l'identifiant par celui renvoyé par la requête précédente si nécessaire
POST http://localhost:3000/api/auth/membre/login
Content-Type: application/json

{
  "numeroCompte": "MW-PRI-SLRKT8", 
  "password": "556677"
}

### Changement de Mot de Passe (Libération/Basculeur)
POST http://localhost:3000/api/auth/membre/change-password
Content-Type: application/json

{
  "numeroCompte": "MW-PRI-SLRKT8",
  "newPassword": "123456"
}

### Connexion avec le Nouveau Mot de Passe
POST http://localhost:3000/api/auth/membre/login
Content-Type: application/json

{
  "numeroCompte": "MW-PRI-SLRKT8",
  "password": "123456"
}
